#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    pairs = 0
    seen = set()
    uniq = [x for x in ar if x not in seen and not seen.add(x)]
    for num in uniq:
        if ar.count(num)%2 == 0:
            pairs += (ar.count(num)//2)
        else:
            pairs += ((ar.count(num)-1)//2)
    return pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
