#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    cValley = 0
    lvl = 0
    foolist = list(s)
    for i in range(n):
        if(foolist[i] == 'U'):
            lvl += 1
        if(foolist[i] == 'D'):
            lvl -= 1
        if(lvl == 0 and foolist[i] == 'U'):
            cValley += 1
    return cValley

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
