#!/bin/python3

import os

def jumpingOnClouds(c,n):
    jumps = 0
    idx = 0
    while idx < n-1:
        if c[idx] == 0 and c[(idx+2)%n] == 0:
            jumps += 1
            idx += 2
        elif c[idx] == 0 and c[(idx+2)%n] == 1:
            jumps += 1
            idx += 1
    return jumps

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c,n)

    fptr.write(str(result) + '\n')

    fptr.close()
