#!/bin/python3

import os

def minimumBribes(q):
    Q = [p-1 for p in q]
    ans = 0
    for i,p in enumerate(Q):
        if p-i > 2:
            print("Too chaotic")
            return 0
        for j in range(max(p-1, 0), i):
            if Q[j] > p:
                ans+=1
            
    print(ans)

if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        n = int(input())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
