#!/bin/python3

import os

def repeatedString(s, n):
    if s == 'a':
        return n
    else:
        foo_string = s.count('a') * (n//len(s)) + s[:n%len(s)].count('a')
        return foo_string

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
